#!/bin/bash
cd /polo-collector; 

lein run /data/polo-store ticker trollbox BTC_XMR BTC_ETH > /var/log/collector.log
#java -Xmx256m -jar target/topiq-standalone.jar /opt/server-config.edn > /var/log/topiq.log
